### PR TITLE
Fix URI.relative_from_me method

### PR DESCRIPTION
**Pull request by jamoralp**
Signed-off-by: Jose Antonio Moral Parras <joseantoniomoralparras@gmail.com>

### CODE REVIEW

**Comment by jamoralp** [comment]
@aranega I noticed this bug while using this tool for a project at work. Feel free to make any changes to it, but this patch worked for me 🙂

**Comment by aranega** [comment]
Hi @jamoralp ,

Thanks so much for the fix! I tried it on the test suite and everything passes except a test in which I need to use your fix with a tiny twist. Just to be sure I will not break something else in your code, would you have a test case or a scenario I could use to replicate your issue?

Thanks again :)

**Comment by jamoralp** [comment]
Good morning @aranega ! Thank you for the quick response 🙂 

This bug came to light when I was trying to load some model from a file. I am afraid my code changed so much that now I am not able to replicate it again... Sorry for that!
My use case is loading OMG's UML model in XMI format, using this library along with PyUML2; and then using it to construct a bunch of classes which represent buses and signals in some embedded system, then saving it as **xmi** file which can be imported by Rhapsody. Really useful stuff 🙂

I would suggest that you upload your required modification, then I can test my use case against it and see if it is still working?

Thank you very much for your help!

**Comment by aranega** [comment]
Good morning @jamoralp !

Thanks for the details! It would have been nice that I can improve the test suite, but I will find a test case for this at some point, I'm sure :) I'll try to force the error. In the meantime, I pushed the twist to your fix on `develop` you can try it already, I hope it works for you. I'm really happy to know that PyEcore is working nice for you (beside that) and that you can go forward with it :).

Thanks again for your PR and your contribution!

**Pull request merged**
