### PR TITLE
Update json.py

### PR DESCRIPTION
**Pull request by jinhu**
fix: serialize enum and load the same object must result in the same object

### CODE REVIEW

**Comment by aranega** [comment]
Hi @jinhu ! Thanks a lot for the PR. At first sight it seems really good, no problem with it, but after I reviewed the code, I already had tests with `EEnum`, and if I follow the emf-json jackson format, the `EEnum` values are serialized only using their name. Consequently, the test that activates your code: the fact that the structure that is decoded is a dict, should never happens. Actually, running my tests, the tests never enter in your branch even if I have test with enumerations. Could you paste me a part of your `.json`, if it's possible of course, and tell me which tool did you use to produce your json? I don't know if it produces an output that matches the emf-json format. If you used the serializer from PyEcore, then I'm sorry, there is perhaps a bug inside it...

**Comment by jinhu** [comment]
Hi, 
The json file was also created by pyecore:

```python
...
    resource_set.resource_factory['json'] = JsonResource
    resource_set.metamodel_registry[rest.nsURI] = rest
    resource = resource_set.create_resource(URI(file_name))
    resource.append(model)
    resource.save()
```
here is the input json file, it's corresponding metadata file 
[bug.zip](https://github.com/pyecore/pyecore/files/5311930/bug.zip)

and my snippet to load json:
```python
    resource_set = ResourceSet()
    resource_set.resource_factory['json'] = JsonResource
    resource_set.metamodel_registry[rest.nsURI] = rest
    rest_resource = resource_set.get_resource(URI(input_path))
    return rest_resource.contents[0]
``` 
loading this file fails with:
```text
Traceback (most recent call last):
  File "C:/sw-dev/thatch/model-text/model_text/transformer.py", line 59, in <module>
    main()
  File "C:/sw-dev/thatch/model-text/model_text/transformer.py", line 54, in main
    result = args.func(args.input_file_name, args.format, args.output_file_name)
  File "C:/sw-dev/thatch/model-text/model_text/transformer.py", line 21, in transform
    model = autobot.load(input_file_name)
  File "C:\sw-dev\thatch\model-text\model_text\rest_swagger\rest_transform_def.py", line 46, in load
    rest_resource = resource_set.get_resource(URI(input_path))
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\resource.py", line 90, in get_resource
    resource.load(options=options)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 36, in load
    self.to_obj(d, first=True)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 171, in to_obj
    self.process_inst(inst, containments, owning_feature)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 182, in process_inst
    elements = [self.to_obj(x, owning_feature=feature)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 182, in <listcomp>
    elements = [self.to_obj(x, owning_feature=feature)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 171, in to_obj
    self.process_inst(inst, containments, owning_feature)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 182, in process_inst
    elements = [self.to_obj(x, owning_feature=feature)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 182, in <listcomp>
    elements = [self.to_obj(x, owning_feature=feature)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 170, in to_obj
    self.process_inst(inst, eattributes)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\resources\json.py", line 179, in process_inst
    inst.eSet(feature, element)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\ecore.py", line 205, in eSet
    self.__setattr__(feature.name, value)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\ecore.py", line 659, in __set__
    instance_dict[name]._set(value)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\valuecontainer.py", line 106, in _set
    self.check(value)
  File "C:\sw-dev\thatch\model-text\venv\lib\site-packages\pyecore\valuecontainer.py", line 71, in check
    raise BadValueError(value, etype, self.feature)
pyecore.valuecontainer.BadValueError: Expected type JSONDataType[EOrderedSet([number=0, string=1, boolean=2, object=3, array=4, file=5, null=6, integer=7])], but got type EEnumLiteral with value object instead for feature <EAttribute type: JSONDataType[EOrderedSet([number=0, string=1, boolean=2, object=3, array=4, file=5, null=6, integer=7])]> of <EClass name="JsonSchema">

Process finished with exit code 1
```

**Comment by aranega** [comment]
@jinhu Thanks so much for the testcase ! I will look what's the problem right away

**Comment by aranega** [comment]
@jinhu ok! I found the bug, it was in the way the `EEnumLiteral` are serialized, not the way they are deserialized. I fixed it on `develop`, but I didn't add a test yet to cover this case. I will do it shortly. At the same time, you can pull modification from`develop`. I'm so sorry for the inconvenience...

**Comment by aranega** [comment]
The fix for this issue is now on master, the code of the JSON resource have been patched :)

**Pull request closed without merging**
